-- create db+schema;;
CREATE DATABASE PO
CREATE SCHEMA PO
USE PO

SELECT * FROM SYS.databases

--CREATE tables	AND INSERT SAMPLE DATA							
CREATE TABLE ADDRESS(
	ID INT PRIMARY KEY IDENTITY(1,1),
	StreetAddress VARCHAR(30) NOT NULL,
	City VARCHAR(10) NOT NULL,
	StateName CHAR(2) NOT NULL,
	Zipcode CHAR(5) NOT NULL
)
INSERT INTO ADDRESS (StreetAddress, City, StateName, Zipcode) VALUES 
('4800 Calhoun Rd', 'Houston', 'TX', 77024),
('4500 University Dr', 'Houston', 'TX', 77004),
('4373 Cougar Village Dr', 'Houston', 'TX', 77204),
('UH Entrance 14', 'Houston', 'TX', 77004),
('4455 University Dr', 'Houston', 'TX', 77204)

CREATE TABLE PACKAGE(
	TrackingNumber char(6) NOT NULL PRIMARY KEY,
	Sender int NOT NULL, 
	Recipient INT NOT NULL,	
	ToAddress int NOT NULL,	
	Descrp varchar(60),	
	Stat tinyint DEFAULT 0 NOT NULL,
	TimeDelivered datetime,
	ShipmentType INT NOT NULL,
	CHECK (Stat <= 5 and Stat >=0)
)
INSERT INTO PACKAGE (TrackingNumber,Sender,	Recipient,ToAddress,Descrp, Stat, SHIPMENTTYPE) VALUES (123456, 1, 2, 3, 'SOME STUFF', 0, 3)

CREATE TABLE SHOP_ITEM(
	ID int NOT NULL PRIMARY KEY IDENTITY(1,1),
	DESCR varchar(30) NOT NULL,
	UnitCost MONEY NOT NULL,
	STOCK int NOT NULL,
)
INSERT INTO SHOP_ITEM(DESCR,UnitCost,STOCK) VALUES
('STAMP', 0.50, 100),
('POSTCARD', 2, 100)

CREATE TABLE SALE(
	ID INT PRIMARY KEY IDENTITY(1,1),
	ITEMID INT NOT NULL,
	QUANTITY INT NOT NULL DEFAULT 1,
	PURCHASE_DATE DATETIME NOT NULL DEFAULT GETDATE()
)

INSERT INTO SALE(ITEMID, QUANTITY) VALUES
(1, 20)

CREATE TABLE EMPLOYEE(
	ID int NOT NULL PRIMARY KEY IDENTITY(1,1), 
	Name varchar(15) NOT NULL,
	PhoneNumber char(10) NOT NULL,
	Address int NOT NULL, 
	Password varchar(20) CONSTRAINT PasswordCheck CHECK (LEN(Password) >= 8) NOT NULL, 
	WorkPlace int NOT NULL 
)
INSERT INTO EMPLOYEE (Name, PhoneNumber, Address,Password,WorkPlace) VALUES ('First Employee', 1234567890, 1, 'idunnowhatpassword', 1)

CREATE TABLE TRACKING_RECORD(
	ID INT NOT NULL IDENTITY(1,1),
	EmployeeID INT NOT NULL,
	TrackingNumber CHAR(6) NOT NULL,
	StoreID INT NOT NULL,
	TimeIn DATETIME NOT NULL DEFAULT GETDATE(),
	TimeOut DATETIME,
	AddressID INT NOT NULL,
	PRIMARY KEY (ID)
) 
INSERT INTO TRACKING_RECORD (EmployeeID, TrackingNumber, StoreID, AddressID) VALUES (1, 123456, 1, 2)

CREATE TABLE SHIPMENT_TYPE(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	DESCR VARCHAR(30) NOT NULL,
	LENGTH DECIMAL(4,2) NOT NULL,
	HEIGHT decimal(4,2) NOT NULL,
	WIDTH decimal(4,2) NOT NULL,
	UNITCOST MONEY NOT NULL,
	EXPRESSCOST MONEY NOT NULL
)
/*weight has to be lower than 150 lbs
//length has to be under 108 inches
//last three possibly yes or no
//Package as in not a letter, anything higher than 15 length, 12 height, .75 girth
*/
INSERT INTO SHIPMENT_TYPE (DESCR, LENGTH, HEIGHT, WIDTH, UNITCOST, EXPRESSCOST) VALUES 
('LETTER', 12.0, 6.0, 0.25, 0.58, $2.0),
('ENVELOPE', 15.0, 12.0, 0.75, 8.95, $10.0),
('SMALL BOX', 8.0, 5.0, 2.0, 9.45, $13.0),
('MEDIUM BOX', 13.0, 11.0, 3.0, 16.0, $20.0),
('LARGE BOX', 23.0, 11.0, 3.0, 21.5, $40.0)

CREATE TABLE POSTAGE(
	ID INT PRIMARY KEY IDENTITY(1,1),
	PKG CHAR(6) NOT NULL,
	WEIGHT DEC(4,2) NOT NULL CHECK (WEIGHT < 70)
)

INSERT INTO POSTAGE(PKG, WEIGHT) VALUES (123456, 4.5)

CREATE TABLE STORE(
	ID int NOT NULL PRIMARY KEY IDENTITY(1,1),
	Supervisor int NOT NULL,
	Address int NOT NULL,
	RegisterCode char(6) NOT NULL,
	PhoneNum char(10) NOT NULL
)
INSERT INTO STORE (Supervisor,Address,RegisterCode, PHONENUM) VALUES (1,2,654321,1234567890)

CREATE TABLE CUSTOMER(
	ID int PRIMARY KEY NOT NULL IDENTITY(1,1),
	Name varchar(15) NOT NULL,
	phoneNumber char(10) NOT NULL,
	email varchar(20) NOT NULL,
	pswrd varchar(20) CONSTRAINT CK_Users_Pswrd CHECK (LEN(Pswrd) >= 8),
	addr int NOT NULL
)
INSERT INTO CUSTOMER (Name, PHONENUMBER, email, pswrd, addr) VALUES
('Snuffles', '0987654321', 'snuffles@gmail.com', 'password1', 4),
('JOSH', '2345678901', 'JOSH@gmail.com', 'password2', 5)

CREATE TABLE PKGSTATUS(
	StatusID TINYint PRIMARY KEY,
	details varchar(20) NOT NULL
)
INSERT INTO PKGSTATUS (StatusID, details) VALUES
(0, 'In Store'),
(1, 'In Transit'),
(2, 'Out For Delivery'),
(3, 'Delivered'),
(4, 'Lost'),
(5, 'Returned')

--add foreign keys
ALTER TABLE STORE
ADD
CONSTRAINT EMP_REF FOREIGN KEY (Supervisor) REFERENCES	EMPLOYEE(ID),
CONSTRAINT STORE_ADDR FOREIGN KEY (Address) REFERENCES ADDRESS(ID)

ALTER TABLE EMPLOYEE
ADD 
CONSTRAINT EMP_STORE FOREIGN KEY (WorkPlace) REFERENCES STORE(ID),
CONSTRAINT EMP_ADDR FOREIGN KEY (Address) REFERENCES ADDRESS(ID)

ALTER TABLE PACKAGE ADD
CONSTRAINT PKG_SENDER FOREIGN KEY (Sender) REFERENCES CUSTOMER(ID),
CONSTRAINT PKG_RCVER FOREIGN KEY (Recipient) REFERENCES CUSTOMER(ID),
CONSTRAINT PKG_TO FOREIGN KEY (ToAddress) REFERENCES ADDRESS(ID),
CONSTRAINT PKGSTAT FOREIGN KEY (STAT) REFERENCES PKGSTATUS(STATUSID),
CONSTRAINT SHPTYPE FOREIGN KEY (SHIPMENTTYPE) REFERENCES SHIPMENT_TYPE(ID)

ALTER TABLE TRACKING_RECORD ADD
CONSTRAINT WHERE_AT FOREIGN KEY (AddressID) REFERENCES ADDRESS(ID),
CONSTRAINT TRCK_PKG FOREIGN KEY (TrackingNumber) REFERENCES PACKAGE(TrackingNumber),
CONSTRAINT CHECKER FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEE(ID),
CONSTRAINT TRCK_STORE FOREIGN KEY (STOREID) REFERENCES STORE(ID)

ALTER TABLE CUSTOMER ADD
CONSTRAINT CUST_ADDR FOREIGN KEY (ADDR) REFERENCES ADDRESS(ID)

ALTER TABLE SALE ADD CONSTRAINT ITEM FOREIGN KEY (ITEMID) REFERENCES SHOP_ITEM(ID)

ALTER TABLE POSTAGE ADD CONSTRAINT PKGBILLED FOREIGN KEY (PKG) REFERENCES PACKAGE(TRACKINGNUMBER)


--for testing
USE MASTER
DROP DATABASE PO

